---
title: "Project Part 1"
output: html_document
date: "2023-02-28"
---

```{r}
if(!require(installr)) {
  install.packages("installr"); 
  require(installr)}
updateR()
```


```{r}
install.packages("rmarkdown")
install.packages("knitr")
install.packages("readxl")
install.packages("moments")
install.packages("corrplot")
install.packages("pso")
install.packages("psych")
install.packages("GPArotation")
install.packages("lavaan")
install.packages("scatterplot3d")
install.packages("corrplot")
install.packages("rgl")
install.packages("moments")


library(rmarkdown); library(knitr); library(readxl)
library(moments); library(corrplot); library(pso)
library(psych); library(GPArotation); library(lavaan); library(scatterplot3d);library(corrplot);library(rgl);library(moments)

```


```{r}
diseasesdata<-  read.csv("C:/Users/seba6366/Desktop/Heart Disease Data Updated.csv")
View(diseasesdata)
View(diseasesdata)
dim(diseasesdata)
diseasesdata

diseasedata<-as.matrix(diseasesdata)
dim(diseasedata)
```
#1
```{r}

#The original dataset had both numerical and text values. We changed all the text values to numerical values. For dimensions with the following names: Heart Disease, Smoking, Alcohol Drinking, Stroke, DiffWalking, Diabetic, Physical Activity, Asthma, KidneyDisease, Skin Cancer, all entries with response 'No' were transformed to '0' and entries with 'Yes' were transformed to 1.

#The dimension named 'Sex' also had text entries named 'female' and 'male'. These were transformed to numerical values - '0' representing 'male' and '1' represents 'female.' 

#The dimension named 'race' was removed from our dataset because it had more than 5 race classifications and we were not very clear about how to change that to numerical variables. In addition to this, race was not a very important dimension for our analysis.

#We transformed dimension 'age' to 'average.age' because the initial data entries for age where classifications.We transformed these classifications to single numbers by finding the average of each age classification. For the age classification "84-above", we simply turned this to average age=84.

#In the original data, Gen health had text entries. The following were transformed to their corresponding numerical value: 'Excellent'=5, 'Very good'=4. 'Good'=4, 'Fair'=1, and 'Poor'=0.

```

#2
```{r}
#1 D evaluation 
apply(X = diseasedata, MARGIN = 2, FUN = mean)
apply(X = diseasedata, MARGIN = 2, FUN = sd)
apply(X = diseasedata, MARGIN = 2, FUN = var)
apply(X = diseasedata, MARGIN = 2, FUN = skewness)
apply(X = diseasedata, MARGIN = 2, FUN = kurtosis)
apply(X = diseasedata, MARGIN = 2, FUN = hist)

#add details
```

#3
```{r}
#1 D outliers

diseasenobinary<-diseasedata[,-c(1,3,4,5,8,9,11,12,15,16,17)]   #Remove dimensions with binary variables
View(diseasenobinary)

which(scale(abs(diseasenobinary[,1]))> qnorm(1-0.00001/2))  #outliers for BMI dimension
#to be
diseasexout<- diseasenobinary[-c(106,562,841,2332,2360,3095,3144,4085,4371,4394,4968,5432,5665,
5701,6228,6348,6669,6987,8313,8356,9089,9255,9359,9500,10146,10660,10782,11163,12128,12789,12930,12994,13262,13338,13696,13846,13868,15435,16075,17549,17768,17980,18291,18348,18928,19133,19218,19321,19522,20087,20154,20788,20834,20943,21096,21222,21228,21916,22164,22323,22443,22450,22583,22896,23286,24009,25748,25872,26123,28289,28463,29647,29672,29882,30066,30755,30899,31087,31633,32726,32843,34223,34302,34643,36281,36392,37221,37313,38124,38171,38362,38422,38566,39468,39640,40387,40555,40707,40802,40974,41068,41100,41313,41718,42102,43460,43782,44701,45605,46638,47579,47760,48245,49287,49866,50057,50138,50212,50230,50372,50484,50543,51028,51039,51041,51047,51335,51470,51576,51640,51822,52006,52311,52415,52536,52642,54014,54063,54727,54987,55269,55523,55959,56021,56877,57130,57197,57211,58287,58846,59259,59395,59847,59986,60138,60225,60411,60486,60586,60647,60701,62626,62710,62847,63204,63401,64198,65114,65465,66275,68284,68359,68493,70245,70595,71186,71646,72092,72201,73478,73987,74365,75473,75519,75833,76074,76771,76792,76884,77272,77723,77892,77955,78002,78008,78055,78251,79171,79226,79546,79691,79751,80096,80117,80506,80945,80978,81032,81175,81263,81472,81542,81633,81740,81949,81952,82201,82734,82741,83371,83572,83964,84200,84579,84777,85581,86284,86451,86583,86976,87009,87147,87174,87642,87972,88336,88568,88816,88929,88977,89525,89557,89627,90015,90091,90147,90438,93237,93668,94131,94174,94997,95534,96627,96666,97096,97734,97809,97938,98890,99837,100304,100391,100537,100548,100668,101769,102321,102616,102836,102838,103035,103164,103177,103464,104069,104264,104268,104319,104331,104541,104617,104896,104900,104944,105009,105029,105044,105058,105059,105360,105477,106467,107037,107382,108221,108882,109177,110039,110464,110840,110996,111361,111510,111622,111958,112699,112936,113100,113539,113596,113649,114088,114411,114693,116509,116549,117166,118110,119483,119962,120433,120620,121145,121223,121339,122049,122823,122827,123192,124008,124041,124062,126212,126476,126492,126662,126897,126992,127938,128369,129731,129894,130077,130344,130892,131300,131807,132580,132734,132867,133018,133856,133998,134098,134174,134467,134779,135151,135842,137347,138049,138548,138831,138945,139160,139226,139408,140049,140210,140799,141880,141906,144098,144356,144408,144861,145895,146314,146470,147049,147449,147786,148038,148276,149046,149049,149072,149194,149781,150607,150699,150948,150983,151165,151923,152329,152459,152940,152974,153060,153099,153140,153144,153465,153600,153634,153791,154134,154380,154606,155492,155740,156094,156396,156755,156850,157197,157433,157682,158025,159258,159303,159392,159674,159942,160001,160172,160231,160361,160594,160753,160947,160957,161067,161271,161331,161882,162129,162314,162370,163341,163496,164796,165124,166132,166397,166802,167578,167765,168413,168570,170126,171329,171363,171706,172897,173163,173437,173761,173859,174092,174541,174978,175205,175734,175963,176301,176389,176478,176957,177478,177485,177628,178538,179374,179553,179584,180854,182326,182491,183030,184437,184600,184780,185100,185237,185430,185478,185698,186065,187407,187465,187828187937,188071,188909,189015,189112,189284,189500,190236,190511,191036,191646,191711,191774,192260,192272,192368,192587,192631,192727,192765,193397,193854,193941,194222,194366,194487,194780,194791,195418,197311,197918,198247,198426,198930,199476,200197,200768,201174,202150,202450,202492,204974,205428,206436,206755,207565,207617,208010,208484,208505,209394,209661,209773,209922,210934,211249,211531,211562,212526,212589,213373,213573,213607,213892,214620,214913,215132,215793,217627,219751,220050,220083,220237,220999,221303,221826,222003,222134,222144,222292,222295,222872,223151,223554,223962,224004,224426,226186,226893,227453,227902,228066,228090,228143,228170,228548,228613,228672,228748,228782,228845,228866,229008,229432,229701,229789,229798,229865,230067,230281,230433,230740,230761,231077,231339,231438,231894,231977,232055,232721,233078,233705,233823,234148,234180,234419,236595,236762,237077,237823,238362,238366,238420,238451,238540,238894,239233,239469,241196,241313,241806,242247,242835,242856,243134,243293,244301,244651,245094,246634,246650,246822,246845,247446,247651,248036,248472,248888,248898,249093,249456,249716,249738,249788,250027,250296,250333,250789,250985,251861,251941,252707,254274,254955,255517,255531,256408,256478,256687,257061,257383,257910,258395,258477,258640,258651,258824,258973,259047,259087,259425,259711,259872,259924,260166,261461,262244,262375,262772,262858,262864,263188,263245,263366,263405,263595,263702,264304,264500,264944,265104,265154,265164,265190,265547,265761,265791,265797,266010,266175,266285,266438,267143,267172,267476,267679,267776,267894,268010,268068,268148,268185,268328,268371,268694,269592,271260,271295,271832,271867,271906,272812,273319,273675,274127,274505,274613,275270,275692,275840,275990,276240,276943,277902,278437,279636,280652,281437,281804,282114,284097,284905,285828,286079,286139,286269,286347,286482,286646,286726,287090,287382,287420,287747,287882,288106,288391,288604,288911,289082,289085,289096,289256,289380,289458,289558,289675,289909,290079,290184,290595,290853,291714,292523,293120,294382,294400,294741,294765,295194,295758,296036,296696,297156,297516,297646,298066,298526,298691,298850,299273,299413,299605,299832,299861,301038,301048,301062,301205,302384,302868,302903,303193,304394,304488,304530,304660,304832,305438,306493,307491,307697,308296,308424,311154,311346,311371,313154,313318,314100,314788,314923,315163,315641,316996,317264,318123,318163,318793,319020,319293,319591),1]
View(diseasexout)
scale(diseasenobinary[,1])
diseasenotliers<-
qnorm(1-0.00001/2)
#still need to ask prof about the so many outliers

#don't check outliers for columns with binary entries only
```
```{r}
which(scale(abs(diseasenobinary[,2]))> qnorm(1-0.0001/2))  #outliers for physical health
#At .01% significance, Physical health does not have any outliers
which(scale(abs(diseasenobinary[,3]))> qnorm(1-0.001/2))  #outliers for mental health
#At .1% significance, Physical health does not have any outliers
which(scale(abs(diseasenobinary[,4]))> qnorm(1-0.01/2))  #outliers for average age
#At 1% significance level, average age does not have any outliers
which(scale(abs(diseasenobinary[,5]))> qnorm(1-0.01/2))  #outliers for general health
#At 1% significance level, general health does not have any outliers
```


```{r}
which(scale(abs(diseasenobinary[,6]))> qnorm(1-0.00001/2))  #outliers for sleep time
#At 1% significance level, sleep level has absolutely many outliers

diseasexousleep<-diseasenobinary[-c(11,263,619,719,734,906,1159,1168,1217,1285,1383,1743,1774,1932,2133,2180,2368,2526,3154,3234,3250,3642,3919,4967,5026,5295,5520,5681,5834,6358,7563,7863,8069,8139,8298,8469,8833,8945,9359,9410,9500,9704,9938,10641,10656,10813,11148,11544,11735,12028,12302,12340,12664,12717,12867,13269,14261,14507,15206,15303,15737,15930,16150,16328,16578,16580,16824,16835,16993,17112,17254,17321,17529,17553,17555,17766,17805,17846,17874,18185,18258,18368,18720,19020,19274,19276,19404,20018,20234,20995,21738,22106,22620,22670,23062,23089,23589,23865,24864,25830,26149,26153,26982,27334,27409,27431,27524,27910,28795,28980,29405,29882,30079,30439,30793,31244,31956,32076,32116,32461,32479,32667,32871,33189,33873,34123,34464,34534,34791,35364,35372,35604,36800,37060,37243,37348,37376,37509,38266,38469,38537,38946,39159,39582,39651,39737,39868,39897,39940,40016,40141,40248,40289,40686,40859,40886,41068,41159,42266,42448,42497,42895,42913,42951,43213,43340,43465,43708,43870,44394,44455,44470,44544,44609,44734,45516,45671,45942,46053,46479,46607,46860,47173,47264,47385,47454,47591,47673,48215,48220,48360,48569,48604,48637,48679,48789,49009,49106,49641,49671,50094,50138,50188,50290,50336,50388,50520,50583,50718,50735,50750,51086,51095,51376,51470,51547,51640,51698,51702,51720,51904,52073,52453,52802,52971,53147,53829,54261,54297,54514,54589,54703,54957,55012,55013,55240,55351,55432,55700,55787,55851,56069,56072,56206,56272,56372,56619,56651,57081,57085,57659,58045,58143,58333,58662,59294,59345,59723,59886,60664,60720,60991,61350,61617,62090,62635,63282,63593,65621,68059,68218,68838,69008,69384,70326,70569,70998,71952,72520,72715,72935,73257,73318,73978,74142,74194,74200,74720,74880,74989,75002,75969,77228,77286,77407,77608,77699,77862,78065,78250,78484,78873,79095,79174,79323,79353,79631,79761,80076,80170,80363,80367,80587,81012,81183,81267,81843,82730,83099,83226,83500,86044,87035,87431,87906,88728,88931,88938,89623,89651,89758,89767,90986,91877,92094,92200,92396,92618,92659,93827,93887,94102,94118,94576,95320,96734,97098,97784,98758,98888,98978,99171,99191,99339,99718,99781,100096,100097,100105,100115,100643,100663,100695,100840,101360,101855,101957,101973,102003,102245,102293,102435,102599,102659,102692,103059,103215,103381,103582,103644,103948,104000,104326,104559,104739,105782,106383,106395,106825,107429,108934,109286,111165,111217,111935,112764,113514,113759,114173,114349,115355,115862,116057,116112,116253,116454,116924,117210,118051,118342,118790,119565,119664,120189,120329,120872,120879,121395,121662,121879,122395,122857,123063,123194,124088,124638,124928,126012,126163,126391,126564,126770,126785,127359,127693,128081,128436,129306,129591,129752,129823,130029,130685,130756,130933,131405,131455,131499,131530,133686,133988,134018,134873,134973,135367,135668,139050,139062,139615,139805,139813,140046,140321,140658,140729,140822,141030,142823,143554,144017,144425,144888,145352,145876,146348,146506,146690,146696,146897,149053,149064,149073,149085,149374,149413,150216,150257,150344,150377,150397,150401,150412,150650,150741,150950,151473,151694,151763,151875,151970,152314,152825,153166,153251,153566,153643,153708,153774,154390,154469,154516,155721,156056,156214,156743,156905,157896,157952,157972,158197,158812,159919,160492,160505,161026,161364,161544,161735,162749,163729,163830,164086,164749,165373,165473,166215,166992,167930,169012,169016,169162,170227,170349,170407,170436,172393,172539,173671,173714,174130,174327,174744,174975,175215,175483,175743,175955,176121,176364,176375,176807,177149,178549,178823,179609,180989,181177,181505,181724,182200,183476,183675,183916,184238,184537,184580,187112,187323,187398,187968,188698,188877,190030,190312,190666,190804,191065,191494,191654,191894,191914,192173,192673,193165,193741,193785,194538,195418,196369,196385,196676,196706,197111,197260,197387,197758,198532,199230,199521,200675,201216,201316,202422,202573,202836,202939,203219,203312,204532,205301,205436,205871,206350,206804,206875,207081,207503,207725,208256,208532,208707,209373,209540,210209,210219,210528,210675),]    #part 1

diseasexousleep<-diseasexousleep[-c(211216,213044,214042,216222,218174,218228,218988,219740,220181,220282,221063,221530,221811,222168,222309,222369,222465,222624,222732,223628,223642,224295,224413,224911,225089,225598,225627,225687,225752,226072,227059,227478,227851,228656,229281,229326,229383,230406,230608,231160,231264,231742,231840,231955,232182,232398,232809,232985,233142,233346,233397,233803,233833,233856,235628,237072,237933,238355,239300,239835,240120,240273,240348,240720,241424,241832,242646,242939,243045,243144,243695,243871,245550,246236,246643,248094,248118,248203,248431,248603,248701,249057,249625,249834,250019,250350,250416,250650,250849,252511,252584,252743,253078,254121,254234,255873,255995,256134,256744,256926,257171,257286,257800,258370,258481,258483,258570,258653,258700,259273,259404,259693,259920,260162,261217,261837,262035,262098,262156,262213,262425,262536,263104,263217,263283,263428,263699,263710,264032,264144,264396,264739,264976,265181,265568,266151,266252,266698,266908,266990,267093,267120,267555,267947,268047,268187,269345,269351,269631,269887,270006,270046,270118,270314,270429,270526,271770,272116,272235,273038,273176,273241,273653,273780,276385,276473,276475,276666,277088,278036,278147,278746,278883,279083,279648,280063,280402,281522,281850,283077,283481,283523,283565,283917,285077,285622,286142,286291,286478,286649,286874,286904,286947,287365,287414,287854,287855,288108,288125,288539,288910,289212,289625,289782,290805,290869,292365,292792,293639,293698,294140,294388,295337,295873,296560,297974,299264,299980,300500,300524,300717,300832,301111,301655,301737,302010,302179,302509,302634,302899,303445,303842,304364,304523,304579,304961,305558,305847,305970,306106,306508,306679,307771,307792,307854,307987,308187,308563,309646,309746,309849,310207,310281,310561,311191,312504,313085,313659,314169,314479,314643,315654,315664,318989,319372),] #continuation of dataset with no BMI outliers
View(diseasexousleep)

#evaluate influence of outliers
mean(diseasedata[,14])
mean(diseasexousleep[,6])
#After having removed outliers, the mean of sleep time decreased by 0.02 units.

var(diseasedata[,14])
var(diseasexousleep[,6])
#After having removed outliers, the variance of sleep time decreased by 0.1727487 units.

sd(diseasedata[,14])
sd(diseasexousleep[,6])
#After having removed outliers, the standard deviation of sleep time decreased by 0.062 units.

skewness(diseasedata[,14])
skewness(diseasexousleep[,6]) 

#After having removed outliers, the skewness of sleep time remained positive and decreased by 0.5737 units. After the removal of outliers, BMI's distribution is closer to being normally distributed than before removing them.

kurtosis(diseasedata[,14])
kurtosis(diseasexousleep[,6])

#After having removed outliers, the kurtosis of sleep time decreased by 3.73 units. Even after the removal of outliers, the sleep time still has a leptokurtic distribution.


```
,
```{r}
```



#4
```{r}
#run a correlation and drop the insignificant ones
findcore <- cor(diseasesdata)    #correlation matrix
findcore


findcore[lower.tri(findcore,diag=TRUE)] <- NA     #drop duplicates (lower triangle)
findcore[findcore == 1] <- NA                     #drop perfect correlations

View(findcore)

findcore<-as.data.frame(as.table(findcore))     #change correlation matrix to a 3 columns table
View(findcore)

findcore <- na.omit(findcore)         #remove the NA values from above 
View(findcore)

findcort<-subset(findcore, abs(findcore$Freq)>0.05)#choose significant values
View(findcort)

findcort<-findcort[order(-abs(findcort[,3])),]      #order by most significant


print(findcort)

corpmatrix<-reshape2::acast(findcort,Var1~Var2, value.var = "Freq")
corrplot(corpmatrix,is.corr=FALSE, method="square",tl.col="black", na.label=" ")

#add summary
#add scatterplots and descriptions-Ndeh and Karen
```

